/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A JSON representation of a JSR configuration file.
 */
export interface JSRConfigurationFileSchema {
  /**
   * The name of this JSR package. Must be scoped
   */
  name: string;
  /**
   * The version of this JSR package.
   */
  version: string;
  exports:
    | string
    | {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^\.(/.*)?$".
         */
        [k: string]: string;
      };
  publish?: {
    /**
     * List of files, directories or globs that will be included in the published package.
     */
    include?: string[];
    /**
     * List of files, directories or globs that will be excluded from the published package.
     */
    exclude?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
